### ISSUE TITLE
TypeError: cannot read properties of undefined (reading 'wait')

### ISSUE THREAD

**Issue by joticajulian** [tenonedesign/fogata-ui#2]
this happens because more koin is tried to be deposited as is available
`TypeError: cannot read properties of undefined (reading 'wait')`
<img width="321" alt="image" src="https://github.com/tenonedesign/fogata-ui/assets/25859602/c0d6abf3-e9c8-4f3c-b0d1-9742eae809d4">

**Comment by tenonedesign** [comment]
Validated balances when modifying stake or reserved koin in 948e02757efe0f9462fb7b2e5ae278f555f29126
